name: Auto Upload Package

on:
  release:
    types: [created]
  workflow_run:
    workflows: ["Auto Release Package"]
    types:
      - completed
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "npm"
          registry-url: https://npm.pkg.github.com/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}